In [1]:
import pandas as pd

Data Link = https://collegescorecard.ed.gov/data/

In [5]:
df= pd.read_csv(r"C:\Users\shivg\pythoncode\naveen\Naveen Python project-5\project-5\CollegeScorecard_Raw_Data\CollegeScorecard_Raw_Data\MERGED2015_16_PP.csv")

D:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (6,9,1725,1726,1727,1728,1729,1743) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [6]:
df.count()

UNITID            7593
OPEID             7593
OPEID6            7593
INSTNM            7593
CITY              7593
STABBR            7593
ZIP               7593
ACCREDAGENCY      6673
INSTURL           7573
NPCURL            7075
SCH_DEG              0
HCM2              7593
MAIN              7593
NUMBRANCH         7593
PREDDEG           7593
HIGHDEG           7593
CONTROL           7593
ST_FIPS           7593
REGION            7593
LOCALE            7147
LOCALE2              0
LATITUDE          7147
LONGITUDE         7147
CCBASIC           7147
CCUGPROF          7147
CCSIZSET          7147
HBCU              7147
PBI               7147
ANNHI             7147
TRIBAL            7147
                  ...
GRADS             2101
ACCREDCODE        6673
OMACHT6_FTFT      3955
OMAWDP6_FTFT      3807
OMACHT8_FTFT      3955
OMAWDP8_FTFT      3807
OMENRYP8_FTFT     3807
OMENRAP8_FTFT     3807
OMENRUP8_FTFT     3807
OMACHT6_PTFT      3955
OMAWDP6_PTFT      2668
OMACHT8_PTFT      3955
OMAWDP8_PTFT      2667
OMENRYP8_PTFT     2667
OMENRAP8_PTFT     2667
OMENRUP8_PTFT     2667
OMACHT6_FTNFT     3955
OMAWDP6_FTNFT     3671
OMACHT8_FTNFT     3955
OMAWDP8_FTNFT     3671
OMENRYP8_FTNFT    3671
OMENRAP8_FTNFT    3671
OMENRUP8_FTNFT    3671
OMACHT6_PTNFT     3955
OMAWDP6_PTNFT     2948
OMACHT8_PTNFT     3955
OMAWDP8_PTNFT     2947
OMENRYP8_PTNFT    2947
OMENRAP8_PTNFT    2947
OMENRUP8_PTNFT    2947
Length: 1805, dtype: int64

In [7]:
df.head(5)

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMENRYP8_FTNFT,OMENRAP8_FTNFT,OMENRUP8_FTNFT,OMACHT6_PTNFT,OMAWDP6_PTNFT,OMACHT8_PTNFT,OMAWDP8_PTNFT,OMENRYP8_PTNFT,OMENRAP8_PTNFT,OMENRUP8_PTNFT
0,100654,100200,1002,Alabama A & M University,Normal,AL,35762,Southern Association of Colleges and Schools C...,www.aamu.edu/,www2.aamu.edu/scripts/netpricecalc/npcalc.htm,...,0.0000,0.1727,0.3909,16.0,0.3125,16.0,0.3125,0.0000,0.0000,0.6875
1,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,Southern Association of Colleges and Schools C...,www.uab.edu,uab.studentaidcalculator.com/survey.aspx,...,0.0102,0.2187,0.1385,248.0,0.3589,248.0,0.4032,0.0444,0.2500,0.3024
2,100690,2503400,25034,Amridge University,Montgomery,AL,36117-3553,Southern Association of Colleges and Schools C...,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,...,0.0125,0.4375,0.0000,36.0,0.5000,36.0,0.5278,0.0278,0.4444,0.0000
3,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,35899,Southern Association of Colleges and Schools C...,www.uah.edu,finaid.uah.edu/,...,0.0124,0.3209,0.1242,131.0,0.3588,131.0,0.3664,0.0382,0.4351,0.1603
4,100724,100500,1005,Alabama State University,Montgomery,AL,36104-0271,Southern Association of Colleges and Schools C...,www.alasu.edu,www.alasu.edu/cost-aid/forms/calculator/index....,...,0.0000,0.3672,0.1977,36.0,0.2778,36.0,0.3056,0.0278,0.5833,0.0833